const GROUND = 330
const BASE_HP = 200

const GAME_KEYS = new Set([
  "KeyA", "KeyD", "KeyW", "KeyU", "KeyI", "KeyO",
  "ArrowLeft", "ArrowRight", "ArrowUp", "Numpad4", "Numpad5", "Numpad6", "Space"
])

const i18n = {
  vi: {
    title: "STICKMAN FIGHTING",
    setupTitle: "THIẾT LẬP TRẬN ĐẤU",
    labelSound: "Âm thanh",
    labelHealth: "Thanh máu",
    labelTime: "Thời gian",
    labelMode: "Chế độ",
    labelLanguage: "Ngôn ngữ",
    btnStart: "BẮT ĐẦU",
    btnAbout: "HƯỚNG DẪN",
    btnRestart: "CHƠI LẠI",
    btnBack: "QUAY LẠI",
    btnBackSetup: "QUAY LẠI THIẾT LẬP",
    mode1: "1 NGƯỜI CHƠI",
    mode2: "2 NGƯỜI CHƠI",
    sec30: "30 giây",
    sec60: "60 giây",
    sec90: "90 giây",
    sec120: "120 giây",
    langVi: "TIẾNG VIỆT",
    langEn: "ENGLISH",
    aboutTitle: "Hướng dẫn chơi",
    aboutDesc: "Chọn chế độ, chiến đấu và hạ gục đối thủ trước khi hết thời gian.",
    guide1Title: "Mục tiêu trận đấu",
    guide1Line1: "- Đánh bại đối thủ bằng cách đưa máu về 0.",
    guide1Line2: "- Nếu hết giờ, bên nào còn nhiều máu hơn sẽ thắng.",
    guide1Line3: "- Nếu hai bên bằng máu khi hết giờ, kết quả là hòa.",
    guide2Title: "Điều khiển người chơi 1",
    guide2Line1: "- A / D: Di chuyển trái phải.",
    guide2Line2: "- W: Nhảy lên.",
    guide2Line3: "- U: Đỡ đòn, I: Đấm, O: Đá.",
    guide3Title: "Điều khiển người chơi 2",
    guide3Line1: "- Mũi tên trái / phải: Di chuyển.",
    guide3Line2: "- Mũi tên lên: Nhảy.",
    guide3Line3: "- Num4: Đỡ, Num5: Đấm, Num6: Đá.",
    guide4Title: "Mẹo chơi nhanh",
    guide4Line1: "- Đỡ đòn sẽ giảm sát thương nhận vào.",
    guide4Line2: "- Đấm để mở combo, đá để đẩy lùi đối thủ.",
    guide4Line3: "- Chỉnh Health và Time trong thiết lập trận đấu để phù hợp."
  },
  en: {
    title: "STICKMAN FIGHTING",
    setupTitle: "BATTLE SETUP",
    labelSound: "Sound",
    labelHealth: "Health Bar",
    labelTime: "Time",
    labelMode: "Mode",
    labelLanguage: "Language",
    btnStart: "START",
    btnAbout: "ABOUT",
    btnRestart: "RESTART",
    btnBack: "BACK",
    btnBackSetup: "BACK TO SETUP",
    mode1: "1 PLAYER",
    mode2: "2 PLAYER",
    sec30: "30 seconds",
    sec60: "60 seconds",
    sec90: "90 seconds",
    sec120: "120 seconds",
    langVi: "VIETNAMESE",
    langEn: "ENGLISH",
    aboutTitle: "HOW TO PLAY",
    aboutDesc: "Choose mode, fight, and knock down your opponent before time runs out.",
    guide1Title: "MATCH OBJECTIVE",
    guide1Line1: "- Defeat your opponent by reducing HP to 0.",
    guide1Line2: "- When time is up, higher HP wins.",
    guide1Line3: "- If HP is equal when time ends, the match is a DRAW.",
    guide2Title: "PLAYER 1 CONTROLS",
    guide2Line1: "- A / D: Move left and right.",
    guide2Line2: "- W: Jump.",
    guide2Line3: "- U: Block, I: Punch, O: Kick.",
    guide3Title: "PLAYER 2 CONTROLS",
    guide3Line1: "- Left / Right Arrow: Move.",
    guide3Line2: "- Up Arrow: Jump.",
    guide3Line3: "- Num4: Block, Num5: Punch, Num6: Kick.",
    guide4Title: "QUICK TIPS",
    guide4Line1: "- Blocking reduces incoming damage.",
    guide4Line2: "- Punch to start combos, kick to push back.",
    guide4Line3: "- Tune Health and Time in BATTLE SETUP to match your style."
  }
}
